name: extended_tabs_example
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  extended_tabs:
    path: ../

  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  ff_annotation_route_library: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
