// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://demogrouppage',
  'fluttercandies://link',
  'fluttercandies://mainpage',
  'fluttercandies://sroll_direction',
];

class Routes {
  const Routes._();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>> keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.'
  ///
  /// [name] : 'fluttercandies://link'
  ///
  /// [routeName] : 'Link'
  ///
  /// [description] : 'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesLink = 'fluttercandies://link';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'set ssroll direction of tabbar and tabView'
  ///
  /// [name] : 'fluttercandies://sroll_direction'
  ///
  /// [routeName] : 'SrollDirection'
  ///
  /// [description] : 'set ssroll direction of tabbar and tabView'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesSrollDirection =
      'fluttercandies://sroll_direction';
}
