// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'pages/main_page.dart';
import 'pages/simple/carousel_indicator.dart';
import 'pages/simple/link.dart';
import 'pages/simple/mainAxisAlignment.dart';
import 'pages/simple/scroll_direction.dart';

FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://CarouselIndicator':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => CarouselIndicatorDemo(),
        routeName: 'CarouselIndicator',
        description: 'Carousel Indicator',
        exts: <String, dynamic>{'group': 'Simple', 'order': 2},
      );
    case 'fluttercandies://MainAxisAlignment':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MainAxisAlignmentDemo(),
        routeName: 'MainAxisAlignment',
        description: 'set MainAxisAlignment for ExtendedTabBar',
        exts: <String, dynamic>{'group': 'Simple', 'order': 3},
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => DemoGroupPage(
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
            safeArguments['keyValue'],
          )!,
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://link':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => LinkDemo(),
        routeName: 'Link',
        description:
            'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MainPage(),
        routeName: 'MainPage',
      );
    case 'fluttercandies://scroll_direction':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => SrollDirectionDemo(),
        routeName: 'ScrollDirection',
        description: 'set scroll direction of tabbar and tabView',
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
