// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import,library_private_types_in_public_api
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://CarouselIndicator',
  'fluttercandies://MainAxisAlignment',
  'fluttercandies://demogrouppage',
  'fluttercandies://link',
  'fluttercandies://mainpage',
  'fluttercandies://scroll_direction',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Carousel Indicator'
  ///
  /// [name] : 'fluttercandies://CarouselIndicator'
  ///
  /// [routeName] : 'CarouselIndicator'
  ///
  /// [description] : 'Carousel Indicator'
  ///
  /// [constructors] :
  ///
  /// CarouselIndicatorDemo : [Key? key]
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const String fluttercandiesCarouselIndicator =
      'fluttercandies://CarouselIndicator';

  /// 'set MainAxisAlignment for ExtendedTabBar'
  ///
  /// [name] : 'fluttercandies://MainAxisAlignment'
  ///
  /// [routeName] : 'MainAxisAlignment'
  ///
  /// [description] : 'set MainAxisAlignment for ExtendedTabBar'
  ///
  /// [constructors] :
  ///
  /// MainAxisAlignmentDemo : [Key? key]
  ///
  /// [exts] : {'group': 'Simple', 'order': 3}
  static const String fluttercandiesMainAxisAlignment =
      'fluttercandies://MainAxisAlignment';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue, Key? key]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.'
  ///
  /// [name] : 'fluttercandies://link'
  ///
  /// [routeName] : 'Link'
  ///
  /// [description] : 'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.'
  ///
  /// [constructors] :
  ///
  /// LinkDemo : [Key? key]
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const String fluttercandiesLink = 'fluttercandies://link';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'set scroll direction of tabbar and tabView'
  ///
  /// [name] : 'fluttercandies://scroll_direction'
  ///
  /// [routeName] : 'ScrollDirection'
  ///
  /// [description] : 'set scroll direction of tabbar and tabView'
  ///
  /// [constructors] :
  ///
  /// ScrollDirectionDemo : [Key? key]
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const String fluttercandiesScrollDirection =
      'fluttercandies://scroll_direction';
}
