// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import,library_private_types_in_public_api
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'pages/main_page.dart';
import 'pages/simple/carousel_indicator.dart';
import 'pages/simple/link.dart';
import 'pages/simple/main_axis_alignment.dart';
import 'pages/simple/scroll_direction.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://CarouselIndicator':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => CarouselIndicatorDemo(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'CarouselIndicator',
        description: 'Carousel Indicator',
        exts: <String, dynamic>{
          'group': 'Simple',
          'order': 2,
        },
      );
    case 'fluttercandies://MainAxisAlignment':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MainAxisAlignmentDemo(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'MainAxisAlignment',
        description: 'set MainAxisAlignment for ExtendedTabBar',
        exts: <String, dynamic>{
          'group': 'Simple',
          'order': 3,
        },
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => DemoGroupPage(
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
            safeArguments['keyValue'],
          )!,
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://link':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => LinkDemo(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'Link',
        description:
            'if link is true and current tabbarview over scroll,it will check and scroll ancestor or child tabbarView.',
        exts: <String, dynamic>{
          'group': 'Simple',
          'order': 0,
        },
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MainPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'MainPage',
      );
    case 'fluttercandies://scroll_direction':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => ScrollDirectionDemo(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'ScrollDirection',
        description: 'set scroll direction of tabbar and tabView',
        exts: <String, dynamic>{
          'group': 'Simple',
          'order': 1,
        },
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
