name: Publishable

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.md"
      - "**.yaml"
      - "**.yml"

jobs:
  publish-dry-run:
    name: Publish dry-run with packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: 'MockCredentialJson'
          flutter: true
          dryRunOnly: true
          skipTests: true
